name: Auto Commit

on:
  schedule:
    - cron: '0 */2 * * *'  # Har kuni soat 00:00 UTC da ishlaydi
  workflow_dispatch:  # Qo‘lda ishga tushirish uchun

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Repository’ni klon qilish
        uses: actions/checkout@v4

      - name: Sana va vaqtni log faylga qo‘shish
        run: echo "$(date) - Solved a new algorithm challenge by Tokhirbek" >> daily_coding_challenges.md

      - name: Git sozlamalari
        run: |
          git config --global user.name "Tokhirbek"
          git config --global user.email "aminjonovtoxirbek@gmail.com"

      - name: Commit va Push qilish
        run: |
          git add .
          git commit -m "Automated commit: $(date)"
          git push
