name: Auto Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Har kuni soat 00:00 UTC da ishlaydi
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Repository’ni klon qilish
        uses: actions/checkout@v4

      - name: Git sozlamalari
        run: |
          git config --global user.name "Tokhirbek"
          git config --global user.email "aminjonovtoxirbek@gmail.com"

      - name: Kun davomida tasodifiy commitlar
        run: |
          NUM_COMMITS=$((RANDOM % 5 + 1))  # Har kuni 1-5 ta commit qilish
          for i in $(seq 1 $NUM_COMMITS); do
            echo "$(date) - Solved a new algorithm challenge by Tokhirbek" >> daily_coding_challenges.md
            git add daily_coding_challenges.md
            git commit -m "Solved a new algorithm challenge by Tokhirbek at $(date +'%Y-%m-%d %H:%M:%S')"
          done
          git push
